### PR TITLE
Fix encoding issue when using authentication.

### LINKED ISSUE #260: Authentication does not work after #259
After #259 authentication using the HTML5 client does not work anymore. 

If I use `xpra attach wss://user@server.de` authentication is fine but using HTML5 client fails. I could not find a way to print the password string which is sent to PAM.

@oskarbraten did you test the PR? If yes: I don't have experience with Javascript however I can try to print the encoded string before and after the PR.

### PR DESCRIPTION
**Pull request by oskarbraten**
Fixes the encoding issue when using authentication by using Uint8ToString from `rencode.js` in the `_process_challenge`-function. Also started removing legacy encoding.

We have to test this thoroughly before merging, as it may have unintended effects that I have yet to discover.

Fixes #260

### CODE REVIEW

File: html5/js/Client.js [hunk 1]
```diff
@@ -2965,10 +2959,10 @@ class XpraClient {
         return;
       }
     }
-    const digest = Utilities.s(packet[3]);
```
Comment (totaam) [inline html5/js/Client.js:2968]: Have you tested with older servers without `rencodeplus`?
This call is present to ensure backwards compatibility.

File: html5/js/lib/rencode.js [hunk 2]
```diff
@@ -253,14 +253,6 @@ function rencode_none() {
...
 }
 
-//turn this flag off to use "rencodeplus" when encoding
-//this will send Uint8Array as 'binary'
-//(decoding is always supported since not having it is free)
-let rencode_legacy_mode = false;
-function rencodelegacy(obj) {
-	rencode_legacy_mode = true;
-	return rencode(obj);
-}
```
Comment (totaam) [inline html5/js/lib/rencode.js:263]: Why are you completely removing `rencode` support?

File: html5/js/lib/rencode.js [hunk 3]
```diff
@@ -271,15 +263,6 @@ function rencode(obj) {
...
 		if(obj.constructor===Uint8Array) {
-			if (rencode_legacy_mode) {
-				//legacy rencode cannot handle bytearrays
-				const CHUNK_SZ = 0x8000;
-				const c = [];
-				for (let i=0; i < u8a.length; i+=CHUNK_SZ) {
-					c.push(String.fromCharCode.apply(null, u8a.subarray(i, i+CHUNK_SZ)));
-				}
-				return rencode_string(c.join(""));
-			}
```
Comment (totaam) [inline html5/js/lib/rencode.js:282]: This removes legacy support - it does not belong in a bug fix.

Comment (oskarbraten) [reply html5/js/lib/rencode.js:282]: Oh, ok. I got the impression that support for legacy mode had already been dropped. I'll update the PR to only contain the bug fix.

Comment (totaam) [reply html5/js/lib/rencode.js:282]: Legacy mode has been dropped from xpra v6, not from v5 due to be released.
The fix should be released for a version that can be used with older servers.
Then we can drop legacy mode.

Comment (oskarbraten) [reply html5/js/lib/rencode.js:282]: Understood, in that case I think reverting #259 is the best course of action.

Comment (totaam) [reply html5/js/lib/rencode.js:282]: Meh. Now I am thinking that we should just merge this and drop all <v5 compatibility.
Those that still need to support older versions can use an older version of the html5 client.

**Review by totaam — APPROVED** [review]
